package com.carilt01.irisframegen.client.iris;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.zip.ZipFile;

public class IrisShaderPreprocessor {


    private static final Logger LOGGER = LoggerFactory.getLogger(IrisShaderPreprocessor.class);

    private static final String VERTEX_SHADER_HEADER_TERRAIN = """
            /* AUTOMATICALLY GENERATED BY IRIS FRAME GEN MOD */
            /* --- Iris Frame Gen Begin --- */
            in vec3 vaPosition;
            in vec2 vaUV0;
            uniform vec3 chunkOffset;
            uniform mat4 modelViewMatrix;
            uniform mat4 projectionMatrix;
            uniform mat4 gbufferPreviousModelView;
            uniform mat4 gbufferPreviousProjection;
            uniform vec3 cameraPosition;
            uniform float near;
            uniform float far;
            out float irisFrameGenOUTdepth;
            /* --- Iris Frame Gen End --- */
            """;

    private static final String VERTEX_SHADER_CORE_TERRAIN = """
                /* --- Iris Frame Gen Begin --- */
                mat4 prevViewProjMatrix = gbufferPreviousProjection * gbufferPreviousModelView;
                mat4 currViewProjMatrix = projectionMatrix * modelViewMatrix;
                vec4 worldPos = vec4(vaPosition + chunkOffset, 1.0);
                vec4 irisFrameGenOUTcurrentPosition  = currViewProjMatrix * worldPos;
                vec4 irisFrameGenOUTpreviousPosition = prevViewProjMatrix * worldPos;
                float distFromCamera = distance(cameraPosition, worldPos.xyz);
                irisFrameGenOUTdepth = irisFrameGenOUTcurrentPosition.z / irisFrameGenOUTcurrentPosition.w * 0.5 + 0.5;
                /* --- Iris Frame Gen End --- */
            """;

    private static final String FRAGMENT_SHADER_HEADER_TERRAIN = """
            layout (rg32f) uniform image2D irisFrameGenOUTmotion;
            uniform float viewWidth;
            uniform float viewHeight;
            uniform sampler2D depthtex0;
            uniform mat4 gbufferProjectionInverse;
            uniform mat4 gbufferPreviousProjection;
            uniform mat4 gbufferPreviousModelView;
            uniform mat4 gbufferModelView;
            uniform float near;
            uniform float far;
            uniform vec3 cameraPosition;
            uniform vec3 previousCameraPosition;
            in float irisFrameGenOUTdepth;
            """;
    private static final String FRAGMENT_SHADER_CORE_TERRAIN = """

        vec2 uv = gl_FragCoord.xy / vec2(viewWidth, viewHeight);
        vec4 ndc = vec4(uv * 2.0 - 1.0, irisFrameGenOUTdepth * 2.0 - 1.0, 1.0);
        vec4 view = gbufferProjectionInverse * ndc;
        view /= view.w;
        vec4 world = inverse(gbufferModelView) * view;
        vec3 cameraDelta = cameraPosition - previousCameraPosition;
        world.xyz += cameraDelta;
        vec4 prevClip =
        gbufferPreviousProjection *
        gbufferPreviousModelView *
        world;
        vec2 currUV = uv;
        vec2 prevUV = prevClip.xy / prevClip.w * 0.5 + 0.5;
        vec2 motion = currUV - prevUV;
        imageStore(irisFrameGenOUTmotion, ivec2(gl_FragCoord.xy), vec4(motion.xy, 0.0, 0.0));
            """;

    // Basic
    private static final String VERTEX_SHADER_HEADER_BASIC = """
            in vec3 vaPosition;
            uniform vec3 chunkOffset;
            uniform mat4 modelViewMatrix;
            uniform mat4 projectionMatrix;
            uniform mat4 gbufferPreviousModelView;
            uniform mat4 gbufferPreviousProjection;
            uniform vec3 cameraPosition;
            uniform float near;
            uniform float far;
            out float irisFrameGenOUTdepth;
            """;

    private static final String VERTEX_SHADER_CORE_BASIC = """
            vec4 worldPos = vec4(vaPosition + chunkOffset, 1.0);
            mat4 currViewProjMatrix = projectionMatrix * modelViewMatrix;
            float distFromCamera = distance(cameraPosition, worldPos.xyz);
            vec4 currentPosition = currViewProjMatrix * worldPos;
            irisFrameGenOUTdepth = currentPosition.z / currentPosition.w * 0.5 + 0.5;
            """;

    private static final String FRAGMENT_SHADER_HEADER_BASIC = """
            layout (rg32f) uniform image2D irisFrameGenOUTmotion;
            uniform float viewWidth;
            uniform float viewHeight;
            uniform sampler2D depthtex0;
            uniform mat4 gbufferProjectionInverse;
            uniform mat4 gbufferPreviousProjection;
            uniform mat4 gbufferPreviousModelView;
            uniform mat4 gbufferModelView;
            uniform float near;
            uniform float far;
            uniform vec3 cameraPosition;
            uniform vec3 previousCameraPosition;
            in float irisFrameGenOUTdepth;
            """;

    private static final String FRAGMENT_SHADER_CORE_BASIC = """
            vec2 uv = gl_FragCoord.xy / vec2(viewWidth, viewHeight);
            vec4 ndc = vec4(uv * 2.0 - 1.0, irisFrameGenOUTdepth * 2.0 - 1.0, 1.0);
            vec4 view = gbufferProjectionInverse * ndc;
            view /= view.w;
            vec4 world = inverse(gbufferModelView) * view;
            vec3 cameraDelta = cameraPosition - previousCameraPosition;
            world.xyz += cameraDelta;
            vec4 prevClip =
            gbufferPreviousProjection *
            gbufferPreviousModelView *
            world;
            vec2 currUV = uv;
            vec2 prevUV = prevClip.xy / prevClip.w * 0.5 + 0.5;
            vec2 motion = currUV - prevUV;
            imageStore(irisFrameGenOUTmotion, ivec2(gl_FragCoord.xy), vec4(motion.xy, 0.0, 0.0));
            """;

    public static String addWarning(String source) {
        source = """
/// ***************************************
/// IRIS FRAME GEN MOD CODE
/// Automatically generated by the preprocessor for
/// motion vectors generation
/// ***************************************
/// If these lines of code are causing an issue, please report to
/// the iris frame gen mod's GitHub!

// ******* BEGIN GENERATED CODE *******
                """ + source + """
// ******* END GENERATED CODE *******
                """;
        return source;
    }

    private static List<String> normalizeLine(String line) {
        line = line.strip();

        // Only care about declarations
        if (!line.startsWith("uniform") &&
                !line.startsWith("in") &&
                !line.startsWith("out") &&
                !line.startsWith("attribute") &&
                !line.startsWith("varying")) {
            return List.of(line.toLowerCase());
        }

        // Example: uniform float near, far;
        int typeEnd = line.indexOf(' ', line.indexOf(' ') + 1);
        if (typeEnd == -1) return List.of(line.toLowerCase());

        String prefix = line.substring(0, typeEnd).trim(); // "uniform float"
        String rest = line.substring(typeEnd).replace(";", "").trim();

        String[] vars = rest.split(",");

        List<String> result = new ArrayList<>();
        for (String var : vars) {
            result.add((prefix + " " + var.trim() + ";").toLowerCase());
        }

        return result;
    }

    private static String addExtensionHeaders(String source) {
        String extensionLine = "#extension GL_ARB_shader_image_load_store : enable";

        String[] lines = source.split("\n");

        int versionIndex = -1;

        for (int i = 0; i < lines.length; i++) {
            if (lines[i].startsWith("#version")) {
                versionIndex = i;
                break;
            }
        }

        List<String> result = new ArrayList<>(List.of(lines));

        if (versionIndex != -1) {
            result.add(versionIndex + 1, extensionLine);
        } else {
            result.addFirst(extensionLine);
        }

        return String.join("\n", result);
    }

    public static String addHeader(String source, String header) {
        header = addWarning(header);

        String[] linesArray = source.split("\n");



        Set<String> lines = new HashSet<>();
        for (String rawLine : linesArray) {
            lines.addAll(normalizeLine(rawLine));
        }

        String[] headerLines = header.split("\n");
        List<String> headerLinesAdd = new ArrayList<>();

        for (String line : headerLines) {
            if (!lines.contains(line.strip().toLowerCase())) {
                // LOGGER.info("Adding: {}", line);
                headerLinesAdd.add(line);
            } else {
                // LOGGER.info("Already exists: {}", line);
            }
        }

        // get where #version header is
        int lineIndex = 0;
        boolean foundVersionHeader = false;
        for (String line : linesArray) {
            if (line.startsWith("#version ")) {
                foundVersionHeader = true;
                break;
            } else {
                lineIndex++;
            }
        }

        if (!foundVersionHeader) {
            lineIndex = 0;
        }

        List<String> linesList = new ArrayList<>(List.of(linesArray));
        linesList.addAll(lineIndex, headerLinesAdd);

        return String.join("\n", linesList);
    }

    public static String addBody(String shaderSource, String source) {
        source = addWarning(source);

        //LOGGER.info("Source: {}", shaderSource);
        int mainIndex = shaderSource.indexOf("void main");

        int openBrace = shaderSource.indexOf("{", mainIndex);

        int depth = 0;
        int closeBrace = -1;

        for (int i = openBrace; i < shaderSource.length(); i++) {
            char c = shaderSource.charAt(i);
            if (c == '{') depth++;
            else if (c == '}') depth--;

            if (depth == 0) {
                closeBrace = i;
                break;
            }
        }

    // insert just before closeBrace
        return shaderSource.substring(0, closeBrace) +
                "\n" + source + "\n" +
                shaderSource.substring(closeBrace);

    }

    public static String preprocessShader(String shaderSource, String path, ZipFile zipFile) {
        String absolutePath = path;

        try {
            String resolvedShaderSource = IncludeResolver.resolve(shaderSource, zipFile);

            if (!absolutePath.contains("program/basic") && !absolutePath.contains("gbuffers_basic") && !absolutePath.contains("program/terrain") && !absolutePath.contains("gbuffers_terrain")) {
                LOGGER.info("Not preprocessing for: {}", absolutePath);
                return resolvedShaderSource;
            }

            if (absolutePath.contains("terrain")) {
                if (absolutePath.endsWith(".vsh")) {
                    String headerAdded = addHeader(resolvedShaderSource, VERTEX_SHADER_HEADER_TERRAIN);
                    String coreAdded = addBody(headerAdded, VERTEX_SHADER_CORE_TERRAIN);
                    String processedSource = addExtensionHeaders(coreAdded);

                    // LOGGER.info("Preprocessed source: {}", processedSource);
                    return processedSource;
                } else if (absolutePath.endsWith(".fsh")) {
                    String headerAdded = addHeader(resolvedShaderSource, FRAGMENT_SHADER_HEADER_TERRAIN);
                    String coreAdded = addBody(headerAdded, FRAGMENT_SHADER_CORE_TERRAIN);
                    String processedSource = addExtensionHeaders(coreAdded);

                    // LOGGER.info("Preprocessed FRAGMENT source: {}", processedSource);
                    return processedSource;
                }
            } else {
                if (absolutePath.endsWith(".vsh")) {
                    String headerAdded = addHeader(resolvedShaderSource, VERTEX_SHADER_HEADER_BASIC);
                    String coreAdded = addBody(headerAdded, VERTEX_SHADER_CORE_BASIC);
                    String processedSource = addExtensionHeaders(coreAdded);

                    // LOGGER.info("Preprocessed vertex basic source: {}", processedSource);

                    return processedSource;
                } else if (absolutePath.endsWith(".fsh")) {
                    String headerAdded = addHeader(resolvedShaderSource, FRAGMENT_SHADER_HEADER_BASIC);
                    String coreAdded = addBody(headerAdded, FRAGMENT_SHADER_CORE_BASIC);
                    String processedSource = addExtensionHeaders(coreAdded);

                    // LOGGER.info("Preprocessed fragment basic source: {}", processedSource);

                    return processedSource;
                }
            }


            return resolvedShaderSource;
        } catch (Exception e) {
            LOGGER.error("Failed to resolve includes: ", e);
            return null;
        }

    }
}
